### ISSUE TITLE
Release 1.1.0 (the first release)

### ISSUE THREAD

**Issue by pavolloffay** [smallrye/smallrye-opentracing#10]
When should the first release be done? Should we wait until https://github.com/smallrye/smallrye-opentracing/issues/5 is resolved?

**Comment by kenfinnigan** [comment]
No, because I expect even with skipping that test here, for Thorntail v2 and v4 it will pass both.

I'd build what you have locally for SmallRye and then work on branches for v2/v4 to bring in SmallRye OpenTracing to verify that what is here works.

Once you have branches for v2/v4 passing the TCK, you can release this and update the branches to the released version and submit PRs.

Sound ok?

**Comment by pavolloffay** [comment]
sounds fine

**Comment by pavolloffay** [comment]
PR to thorntail v2 https://github.com/thorntail/thorntail/pull/1045. Locally all tcks are passing, thanks to @mkouba!

https://github.com/thorntail/thorntail/tree/4.x still uses old MP 1.0. I would recommend first bumping the version as there are breaking changes in OpenTracing API and this will also require bumping version of Jaeger which unfortunately also contains breaking changes.

**Comment by pavolloffay** [comment]
As the current master/head implements MP-OT 1.1 I have adjusted the title to 1.1.0 to follow versioning schema.

**Comment by kenfinnigan** [comment]
Thanks.

If the two branches for v2 and v4 are passing it's safe to release SmallRye OT and update to use the released version

**Comment by pavolloffay** [comment]
4.x is not done yet first have to go in this https://github.com/thorntail/thorntail/pull/1050.

**Comment by pavolloffay** [comment]
Can somebody have a glance at thorntail PRs and give me green to release this? 

cc) @kenfinnigan @mkouba

**Comment by pavolloffay** [comment]
https://github.com/jpkrohling as you are working on WF subsystem using this library do you want me to wait until the first release to confirm it works for you fine?

**Comment by kenfinnigan** [comment]
Please don't. We need these updates in Thorntail asap.

If there are problems discovered by other usages later we can include fixes and re-release

**Comment by pavolloffay** [comment]
The release is done:

https://oss.sonatype.org/#nexus-search;gav~io.smallrye~smallrye-opentracing~~~~kw,versionexpand
