### ISSUE TITLE
Support Zipkin aka b3 wire format

### ISSUE THREAD

**Issue by svenhaag** [smallrye/smallrye-opentracing#120]
Hi, please support the b3-propagation wire format:
https://github.com/openzipkin/b3-propagation

**Comment by kenfinnigan** [comment]
B3 is already supported with OpenTracing I believe, as I've used it when deploying to Istio in the past

**Comment by svenhaag** [comment]
Hi @kenfinnigan, the spec does not make any statement about the wire format, so it is up to the implementation if it supports b3 or whatever. Does SmallRye support it? How do I enable/configure it? Thanks.

**Comment by pavolloffay** [comment]
Smallrye is just instrumentation. The propagation protocol has to be supported by tracer implementation you choose to use with Smallrye. There is nothing to do in this project regarding this.

**Comment by svenhaag** [comment]
Maybe you could document how to link SmallRye with Tracer? Or were can I find it? I guess its SPI magic?

**Comment by pavolloffay** [comment]
https://github.com/smallrye/smallrye-opentracing#tracer-producer
