### ISSUE TITLE
Zipkin Integration

### ISSUE THREAD

**Issue by agentS** [smallrye/smallrye-opentracing#122]
Hi,

[Since I got redirected here from the Quarkus issue tracker](https://github.com/quarkusio/quarkus/issues/8053#issuecomment-602244469), I hope that my issue is in the right place. A friend of mine and I are developing a mini project for one of our university's classes and we want to demonstrate distributed tracing across various services. Since [IBM's OpenLiberty](https://openliberty.io) which the other service is based upon has excellent support for [Zipkin](https://zipkin.io/), we want to use Zipkin instead of Jaeger for tracing; both servers implement the OpenTracing standard.

However, I failed how to figure out a way to make my Quarkus-based application send its traces to Zipkin. I tried setting the configuration parameter `quarkus.jaeger.endpoint` to various values (including `http://127.0.0.1:9411/api/v2/spans`, and `http://127.0.0.1:9411/zipkin/api/v2/spans`), but none of them worked. The configuration for Quarkus' OpenTracing extension is [described in a dedicated guide](https://quarkus.io/guides/opentracing#configuration-reference).

Therefore, I would be most grateful if somebody could provide me a description on how to set the Microprofile OpenTracing client to the Zipkin collector. Thank you so much!

**Comment by pavolloffay** [comment]
Let's talk in https://github.com/quarkusio/quarkus/issues/8053. `SmallRye-OpenTracing` is vendor neutral and can work with any tracer implementation.
