### ISSUE TITLE
Provide javax.enterprise.inject.spi.Extension to install CDI interceptor?

### ISSUE THREAD

**Issue by pavolloffay** [smallrye/smallrye-opentracing#13]
Should the imlp provide `javax.enterprise.inject.spi.Extension` which would install CDI interceptor? 

```
public class SmallRyeTracingCDIExtension implements Extension {

  private static final Logger logger = Logger.getLogger(OpenTracingCDIExtension.class);

  public void observeBeforeBeanDiscovery(@Observes BeforeBeanDiscovery bbd, BeanManager manager) {
    bbd.addAnnotatedType(manager.createAnnotatedType(SmallRyeTracingCDIInterceptor.class));
  }
}
```

The vendor has to also provide CDI extension to load CDI tracer producer. Are multiple extensions loaded? 

cc @mkouba

**Comment by mkouba** [comment]
> Are multiple extensions loaded?

Yes. A CDI extension is basically a service provider and the CDI container must load all extensions at the beginning of the app init.

> Should the imlp provide javax.enterprise.inject.spi.Extension which would install CDI interceptor?

Well, it depends on how much work you expect to be done by an integrator ;-)

I'd say _yes_ and we already do this for example in [smallrye-fault-tolerance](https://github.com/smallrye/smallrye-fault-tolerance/blob/master/implementation/src/main/java/io/smallrye/faulttolerance/HystrixExtension.java#L68).

Also note that ShrinkWrap's `ManifestContainer.addAsServiceProvider()` does overwrite the previous value. See https://github.com/shrinkwrap/shrinkwrap/issues/112. Keep this in mind when working with Arquillian ;-)

**Comment by pavolloffay** [comment]
I haven't used `SmallRyeTracingCDIInterceptor` in Thorntail v4 at all. The implementation there is customized and it intercepts different bean types via `SpanHandler`.

**Comment by mkouba** [comment]
If so then it does not make sense to register the interceptor automatically. It wouldn't hurt to mention this in docs though ;-)

**Comment by pavolloffay** [comment]
There are instructions how to register CDI interceptor https://github.com/smallrye/smallrye-opentracing#cdi, What else should it contain?

**Comment by mkouba** [comment]
Ah ok, it's part of the readme. I had official docs in mind..

**Comment by radcortez** [comment]
OpenTracing is discontinued, so SmallRye OpenTracing is in maintenance mode until we do a complete transition to OpenTelemetry. For this reason, we are not adding new features.
