### ISSUE TITLE
SmallRyeRestClientListener requires CDI

### ISSUE THREAD

**Issue by knutwannheden** [smallrye/smallrye-opentracing#134]
The `SmallRyeRestClientListener` class currently requires CDI to be initialized. In a plain JUnit test, for instance, this is not necessarily the case. And as a result, when trying to create a `RestClient` using `RestClientBuilder` a runtime exception is thrown.

https://github.com/smallrye/smallrye-opentracing/blob/662328c061fa41f34ec39a1cfcde358ada496ec0/implementation/src/main/java/io/smallrye/opentracing/SmallRyeRestClientListener.java#L24

I think it would probably be better to use `GlobalTracer.get()` instead of `CDI.current().select(Tracer.class).get()` for this reason.

See also https://github.com/eclipse/microprofile-rest-client/issues/278.

**Comment by pavolloffay** [comment]
@knutwannheden would you like to submit a fix?

**Comment by radcortez** [comment]
OpenTracing is discontinued, so SmallRye OpenTracing is in maintenance mode until we do a complete transition to OpenTelemetry. For this reason, we are not adding new features.
