### ISSUE TITLE
NPE on CDI Interceptor

### ISSUE THREAD

**Issue by jpkrohling** [smallrye/smallrye-opentracing#17]
When running the test `org.jboss.as.test.smoke.managedbean.ManagedBeanTestCase` from the WildFly smoke tests, I get the following NPE:

```
java.lang.NullPointerException
	at io.smallrye.opentracing.SmallRyeTracingCDIInterceptor.isTraced(SmallRyeTracingCDIInterceptor.java:65)
	at io.smallrye.opentracing.SmallRyeTracingCDIInterceptor.interceptTraced(SmallRyeTracingCDIInterceptor.java:29)
```

Looks like this method (`SmallRyeTracingCDIInterceptor#isTraced()`) needs a null-guard for `classTraced`.

**Comment by pavolloffay** [comment]
Can you please add a link to `ManagedBeanTestCase` or a sample code of traced CDI class?

**Comment by jpkrohling** [comment]
Sure:

https://github.com/wildfly/wildfly/blob/b77de1838c4ebf8a7144cebc27200b10c914dd90/testsuite/integration/smoke/src/test/java/org/jboss/as/test/smoke/managedbean/ManagedBeanTestCase.java#L41-L68
