### ISSUE TITLE
We need a v2 release which includes the correction already back ported to v1

### ISSUE THREAD

**Issue by Rupert-RR** [smallrye/smallrye-opentracing#193]
#173 has already been backported into v1 with a release and has been merged into `master` but as yet there is no v2 release which incorporates it. We could do with this for Quarkus.

**Comment by Ladicek** [comment]
I think this makes sense and is just a matter of doing a release. The `main` branch only contains some version bumps and the fix from #173. WDYT @radcortez?

**Comment by radcortez** [comment]
Yes, we can do it. I'll take care of it.

**Comment by Ladicek** [comment]
Thanks!

**Comment by radcortez** [comment]
Release: https://github.com/smallrye/smallrye-opentracing/releases/tag/2.0.1. I'll update the dependency in Quarkus.
