### ISSUE TITLE
Remove CDI dependency from JAX-RS module

### ISSUE THREAD

**Issue by jpkrohling** [smallrye/smallrye-opentracing#20]
The JAX-RS integration done by the `SmallRyeTracingDynamicFeature` requires CDI by calling `CDI.current().select(Tracer.class)`. This assumes that the CDI bean manager has finished booting and has a tracer ready.

Instead, it would be better to get it from the servlet context. This way, a tracer initializer can be installed via a `ServletContextListener`, which is guaranteed to run before the `DynamicFeature` if it injects a `@Context ServletContext servletContext`.

Reference from https://github.com/wildfly/wildfly/pull/11544: https://gist.github.com/jpkrohling/d05d056be039de8e10222899e536a82e

**Comment by kenfinnigan** [comment]
I'm not sure that would be a good idea given that MicroProfile makes no guarantees about Servlets being available.

Granted most JAX-RS implementations are based on Servlets, but my understanding is the JAX-RS spec doesn't actually have a dependency of any kind on the Servlet spec.

**Comment by jpkrohling** [comment]
Does it make guarantees about the presence of a bean manager and/or guarantees about its lifecycle?

**Comment by kenfinnigan** [comment]
CDI is always guaranteed to be present with MP.

In terms of lifecycle, the only spec that's currently intended to be used without the app having been started is Config. That's why Config doesn't rely on CDI to bootstrap itself

**Comment by jpkrohling** [comment]
The solution I have for WildFly doesn't seem to apply here then, but the main problem still remains. Using `CDI.current().select(Tracer.class)` to get a Tracer may cause problems if the DynamicFeature is executed before the Tracer is ready.

**Comment by pavolloffay** [comment]
Maybe context provider could be used to provide the tracer. e.g. via `@Context Tracer tracer`

**Comment by radcortez** [comment]
OpenTracing is discontinued, so SmallRye OpenTracing is in maintenance mode until we do a complete transition to OpenTelemetry. For this reason, we are not adding new features.
