### ISSUE TITLE
Mark the interceptor as bean, so that it can be referred by external modules

### ISSUE THREAD

**Issue by jpkrohling** [smallrye/smallrye-opentracing#21]
Reference: #19 . 

When smallrye-tracing is included as a JAR in a deployment, and another JAR attempts to add the CDI extension to its `bean.xml`, CDI (or only Weld?) complains that the extension isn't on a bean archive. Ideally, the smallrye-tracing would include a bean.xml and/or a `@Dependent` annotation to the interceptor.

A possible initial implementation can be seen on #19, but that causes the TCK to fail.

**Comment by pavolloffay** [comment]
@jpkrohling was it done as part of #25 ?

**Comment by jpkrohling** [comment]
Yes :)
