### ISSUE TITLE
Use invocation context's context data to store the span context

### ISSUE THREAD

**Issue by jpkrohling** [smallrye/smallrye-opentracing#22]
The interceptor provided by this module works almost perfectly as is for EJBs as well. One case where it does *not* work is in async EJBs. The [`opentracing-contrib/java-ejb`](https://github.com/opentracing-contrib/java-ejb/blob/master/opentracing-ejb/src/main/java/io/opentracing/contrib/ejb/OpenTracingInterceptor.java) one supports that, by making use of the `InvocationContext`'s context data.

**Comment by radcortez** [comment]
OpenTracing is discontinued, so SmallRye OpenTracing is in maintenance mode until we do a complete transition to OpenTelemetry. For this reason, we are not adding new features.
