### ISSUE TITLE
Configure release

### ISSUE THREAD

**Issue by pavolloffay** [smallrye/smallrye-opentracing#3]
Configure release of this artifact

**Comment by kenfinnigan** [comment]
It's now setup for releasing in Semaphore.

Before a release the version will need to be changed to 1.0.0-SNAPSHOT in preparation for releasing 1.0.0 by the Semaphore deployment process

**Comment by pavolloffay** [comment]
Is this https://github.com/smallrye/smallrye-health/blob/master/release.sh  required?

**Comment by kenfinnigan** [comment]
No, releases are triggered from a button in Semaphore

**Comment by pavolloffay** [comment]
thanks @kenfinnigan
