### ISSUE TITLE
Context propagation for fault-tolerance

### ISSUE THREAD

**Issue by pavolloffay** [smallrye/smallrye-opentracing#30]
On the spec level this should be covered in https://github.com/eclipse/microprofile-opentracing/issues/108.

As it might take more time we could implement a custom context propagation in smallrye using HystrixConcurrentStrategy e.g. https://github.com/OpenFeign/feign-opentracing/blob/master/feign-hystrix-opentracing/src/main/java/feign/opentracing/hystrix/TracingConcurrencyStrategy.java.

**Comment by Ladicek** [comment]
In SmallRye Fault Tolerance 2.x, we had a custom `HystrixConcurrencyStrategy` (https://github.com/smallrye/smallrye-fault-tolerance/blob/2.x/implementation/src/main/java/io/smallrye/faulttolerance/tracing/TracingConcurrencyStrategy.java).

In SmallRye Fault Tolerance 4.x, we integrate OpenTracing via MicroProfile Context Propagation (https://github.com/smallrye/smallrye-fault-tolerance/blob/master/implementation/tracing-propagation/src/main/java/io/smallrye/faulttolerance/tracing/TracingContextProvider.java).

**Comment by radcortez** [comment]
OpenTracing is discontinued, so SmallRye OpenTracing is in maintenance mode until we do a complete transition to OpenTelemetry. For this reason, we are not adding new features.
