### ISSUE TITLE
RestClientBuilder.newBuilder().build(Intf.class) fails with IllegalStateException("Unable to access CDI")

### ISSUE THREAD

**Issue by doychin** [smallrye/smallrye-opentracing#57]
When REST client is used without CDI container RestClientBuilder.newBuilder().build(Intf.class) fails with IllegalStateException("Unable to access CDI"). This happens if for some reason opentrace implementation is added to the class path for example when you try to run Arquilian test as client.

**Comment by kenfinnigan** [comment]
This sounds like fixing a project classpath issue by changing the implementation.

There should not be a situation where this is used without CDI present

**Comment by Ladicek** [comment]
I've seen other people using MP RestClient in tests, outside of the runtime. It's a mistake that's too easy to make.

**Comment by doychin** [comment]
This is from MP RestClient specification: The   MicroProfile   Rest   Client   can   be   used   as   a   standalone   technology.   That   means   that   an implementation could work without CDI, MicroProfile Config, etc.

**Comment by doychin** [comment]
I use thorntail for my app . Up to 2.3.0 there was no such issue. After switching to 2.4.0 all tests that are marked as RunAsClient fail because opentrace libraries are added to the class path used to run test code. in my pom.xml I have only dependencies from thorntail.io group. All other dependencies are not related to microprofile in any way.

**Comment by kenfinnigan** [comment]
I've always disagreed with that statement. And will be looking to change it going forward
