### ISSUE TITLE
Update OpenTracing to 0.33.0

### ISSUE THREAD

**Issue by gsmet** [smallrye/smallrye-opentracing#85]
Hi,

Is there a reason why we don't update to a more recent version of OpenTracing? I see 0.33 was released a while ago.

We would like to upgrade in Quarkus but better do it upstream.

Thanks!

**Comment by Ladicek** [comment]
My understanding is that MP OpenTracing stays on 0.31, because the subsequent versions are backwards incompatible, and OpenTracing is already superseded by OpenTelemetry.

But @pavolloffay surely knows better than me :-)

**Comment by pavolloffay** [comment]
@Ladicek summarized it well.

In MP-OT community we are working on the next steps how to proceed. The details should be available soon. I will keep you posted.

**Comment by iabughosh** [comment]
Does the next update will help me to log trace_id and span_id into slf4j-logs/Quarkus.

**Comment by pavolloffay** [comment]
It should. However, quarkus already supports MDC logging with traceids. It's using Jaeger integration directly rather than OT API.
